### ISSUE TITLE
Right Enter button isn't working

### ISSUE THREAD

**Issue by Vaporizadr** [decentraland/explorer-desktop#104]
### What happened?

Hello, i'm testing the newest Decentraland client and I just noticed that the right Enter button isn't working to open chat, like in the website. Please fix this, thanks!

### Steps to reproduce

Be ingame (like wondermine), press right Enter button. Nothing happens, instead of opening the chat window like the regular Enter.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3500X 6-Core Processor 

### GPU

Radeon RX 570 Series 8171MB

### RAM

16318MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-7e33653

### Realm

dg

### NameTag

Vapo#42d4

**Comment by JAXSCOPES-DCL** [comment]
its working for me, try refreshing the game.

**Comment by xavi-dcl** [comment]
Seems it cannot be reproduced
