### ISSUE TITLE
Switching servers in ICE poker 

### ISSUE THREAD

**Issue by JAXSCOPES-DCL** [decentraland/explorer-desktop#107]
### What happened?

When switching between servers within the Stronghold ICE Poker UI it boots up my brave instead of switching servers.

### Steps to reproduce

Jump into Stronghold ICE poker parcel and try to find an open table with the (BLUE) tab that states "See Other Servers" and try to switch it will then pull up your main browser.

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 5600G with Radeon Graphics 

### GPU

NVIDIA GeForce RTX 3060 12142MB

### RAM

16272MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-7e33653

### Realm

dg

### NameTag

JAXSCOPES#e23c

**Comment by Reach2N** [comment]
Hey, you can change the servers/realms by pressing the Esc button, and on the left top corner, you'll see "server: xxx" and xxx is your current server/realm you're on. Click on it and choose which server you want to play. Thanks

**Comment by pravusjif** [comment]
This is because the scene is triggering a URL, not an issue of the Decentraland client.
Althought I know a fix is on the works for scenes to be able to trigger realm changes.
