### ISSUE TITLE
Hitting ESC key opens Explore window instead of giving you mouse control

### ISSUE THREAD

**Issue by rdixon22** [decentraland/explorer-desktop#108]
### What happened?

In the Desktop Client, hitting the ESC key opens the Explore window. But in the web client it gives you mouse control so you can click on UI elements.

For example to open your Inventory panel in WonderMine you now have to:
* Hit ESC
* Wait for the Explore window to open
* Hit the X button to close the Explore window
* Hit the Inventory button to show your inventory

### Steps to reproduce

Got to the WonderMine game, then hit ESC.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

### GPU

Radeon (TM) RX 480 Graphics 8171MB

### RAM

32730MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-7e33653

### Realm

unicorn

### NameTag

Testor#1c75

**Comment by pravusjif** [comment]
We should check if we have 2 systems checking for the ESC input at the same time to unlock mouse & trigger menu

**Comment by pravusjif** [comment]
This issue will be tackled at https://github.com/decentraland/unity-renderer/issues/2017
