### ISSUE TITLE
Typing a number in the chat box triggers an emote

### ISSUE THREAD

**Issue by rdixon22** [decentraland/explorer-desktop#109]
### What happened?

I tried to type /goto -29,55 in the chat box. The numbers did not appear and emote animations were triggered instead. 

### Steps to reproduce

Open the chat box and type /goto - and then a number.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

### GPU

Radeon (TM) RX 480 Graphics 8171MB

### RAM

32730MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-7e33653

### Realm

unicorn

### NameTag

Testor#1c75

**Comment by kuruk-mm** [comment]
This happens on web too.

It was reported here: https://github.com/decentraland/unity-renderer/issues/1954

Closing because of duplicating.
