### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by dogesv** [decentraland/explorer-desktop#115]
### What happened?

CPU 100%

### Steps to reproduce

CPU 100%

### Operating System

client win11

### Wallet

Wallet Connect

### CPU

AMD Ryzen 5 3600 6-Core Processor

### GPU

Radeon RX 580

### RAM

16G

### Kernel Version

latest

### Unity Version

latest

### NameTag

guy #30d3

**Comment by kuruk-mm** [comment]
Closing. If you have 100% CPU usage even with VSync, please re-open the issue.
