### ISSUE TITLE
Some meshes are rendered black or way darker in desktop client

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#119]
Genesis Plaza
![image (2).png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/b2d5af38-9cf6-4adf-bc40-1d3fc36caba8)

Salmonomicon (monster eyes emissive ray)
![slack_4iy2sUGdXF.jpg](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/01c7f777-438d-4a53-ba8f-64a3d38f2c44)

We should check if the project settings, or skybox reflections (the procedural skybox generates a cubemap in runtime) may be involved in this.

**Let's create a new visual test to catch this there for the future**. Maybe it should be specific to desktop (since this renders fine in the web client)

**Comment by pravusjif** [comment]
Another report of this same issue:

![image (3)](https://user-images.githubusercontent.com/1031741/156836062-271d907d-955a-4f8a-9935-8366e4038bce.png)

HOT Pink Zebra Babydoll Top - https://market.decentraland.org/contracts/0x5575a70adba24e062c50e10dae942e0b1b206e88/items/0 
HOT Pink Zebra Babydoll Boots - https://market.decentraland.org/contracts/0x5575a70adba24e062c50e10dae942e0b1b206e88/items/1 
HOT Blue Zebra Babydoll Top - https://market.decentraland.org/contracts/0x5575a70adba24e062c50e10dae942e0b1b206e88/items/3 
HOT Blue Zebra Babydoll Boots - https://market.decentraland.org/contracts/0x5575a70adba24e062c50e10dae942e0b1b206e88/items/2

**Comment by Kinerius** [comment]
Reopening this issue since it's not fixed yet
