### ISSUE TITLE
App crash “a Javascript error occurred in the main process”

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#120]
- For some users this happen on the first desktop client/launcher launch.
- A user reported that after restarting the computed and running the app as administrator this error didn’t show up again

![Capture1.JPG](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/546e5419-61fe-4e51-8a45-09774ac8bdeb)

![unknown.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/14c78641-adba-4498-846e-dc4b8586c28c)

**Comment by kuruk-mm** [comment]
Looks like it's a permission issue.

We should show a warning if you don't have the permissions to open another executable.

**Comment by pravusjif** [comment]
I thinks this is not happenning anymore

**Comment by xavi-dcl** [comment]
Closing, please reopen if it reoccurs
