### ISSUE TITLE
Analyze macOS app signing requirements

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#129]
### PROBLEM 1
When a user installs the macOS desktop client for the first time they 100% of the time get this error message and that’s because the application is not signed with a verified developer signature.

![Screen Shot 2022-08-25 at 16 35 16](https://user-images.githubusercontent.com/1031741/186762387-ab825fb4-1924-4da5-8ecb-74b1c3ecdab3.png)

Due to that error, most of the time people think the client is broken or a virus and they don’t know how to proceed.

### PROBLEM 2
The current launcher can't auto-update its version because it's not a signed application, so currently a warning is shown when the current version opened is not the latest one, indicating that a newer version should be manually downloaded from Decentraland's website.

------------------------------

This issue is to analyze exactly what is needed to solve those problems. 
What we initially thought is needed is:
- An apple developer account verified to be able to sign and distribute applications
- Sign the launcher (@kuruk-mm is the person who implemented the launcher and knows it the most)
- Maybe also sign our macOS unity build (@dalkia can help with that)

After reading the apple documentation (or maybe even testing signing something like the launcher) this issue may be closed and and new specific issues for the different things needed to solve the initial problem could be created and tackled.

**Comment by kuruk-mm** [comment]
We need an Apple developer user for signing MacOS. Electron build will do the rest.

More information: https://www.electron.build/code-signing

**Comment by pravusjif** [comment]
After being able to sign the application as a verified developer, this problem should also be solved:
![Screen Shot 2022-08-25 at 16 35 16](https://user-images.githubusercontent.com/1031741/186762387-ab825fb4-1924-4da5-8ecb-74b1c3ecdab3.png)

**Comment by pravusjif** [comment]
Updated description with more detailed info

**Comment by Antivortex** [comment]
We have to:

1) Create an organization Apple ID, I could not pass 2FA in appstores e-mail to do that for now
2) Enroll to Apple Development Program. For that we need some legal information I requested from Mariano
3) Generate certificates for our apps
4) Learn how to sign an app with this certificate and make it part of CI/CD pipeline
5) Learn how to use Apple notary service to scan application for malware and attach a notary ticket to it

**Comment by Antivortex** [comment]
We have to:

1) Create an organization Apple ID, I could not pass 2FA in appstores e-mail to do that for now
2) Enroll to Apple Development Program. For that we need some legal information I requested from Mariano
3) Generate certificates for our apps
4) Learn how to sign an app with this certificate and make it part of CI/CD pipeline
5) Learn how to use Apple notary service to scan application for malware and attach a notary ticket to it

**Comment by Antivortex** [comment]
Update:

Our lawyer Mariano told me that we do not have a D-U-N-S number for our organization but we need it in order to enroll to Apple Development Program. He is about to figure out how can we get it.
