### ISSUE TITLE
Compass bug

### ISSUE THREAD

**Issue by Titan0429** [decentraland/explorer-desktop#134]
### What happened?

the compass does not show location or direction moving

### Steps to reproduce

open the game

### Operating System

Windows 11   64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

### GPU

NVIDIA GeForce GTX 1660 SUPER 5992MB

### RAM

12195MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-80529f2

### Realm

dg

### NameTag

Titan0429#6908

**Comment by olavra** [comment]
Hi @Titan0429 

With the compass you mean the minimap shown in the top left corner of the screen?
![image](https://user-images.githubusercontent.com/41490935/156565363-63e93838-cc04-4d7e-9e13-93b5b62f4a07.png)
![image](https://user-images.githubusercontent.com/41490935/156565538-8e46e4fa-ae6a-468a-ba31-c75d71afcc67.png)

If that is the case, this is a know issue. Can be tracked here:
https://github.com/decentraland/unity-renderer/issues/1927

Thanks for your feedback!

**Comment by pravusjif** [comment]
This issue has been fixed at https://github.com/decentraland/unity-renderer/pull/1975
