### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by Titan0429** [decentraland/explorer-desktop#135]
### What happened?

While playing desktop game crashed.

### Steps to reproduce

not sure. I have a screenshot of it but cant attach pics here

### Operating System

Windows 11 (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

### GPU

NVIDIA GeForce GTX 1660 SUPER 5992MB

### RAM

12195MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-80529f2

### Realm

dg

### NameTag

Titan0429#6908

**Comment by kuruk-mm** [comment]
Can you share your logs?

Location: `%USERPROFILE%\AppData\LocalLow\Decentraland\Decentraland\Player.log`

**Comment by pravusjif** [comment]
We'll be tracking this crash at https://github.com/decentraland/explorer-desktop/issues/179
