### ISSUE TITLE
Windows Defender blocks desktop client installer

### ISSUE THREAD

**Issue by maraoz** [decentraland/explorer-desktop#136]
### What happened?

![image](https://user-images.githubusercontent.com/287189/156462771-5d770e48-6cf9-460a-9c4b-418b7bc18b82.png)

### Steps to reproduce

1. Download desktop client
2. click on installer
3. popup screenshoted above appears

### Operating System

Windows 10 Pro

### Wallet

Wallet Connect

### CPU

-

### GPU

-

### RAM

-

### Kernel Version

-

### Unity Version

-

### Realm

-

### NameTag

-

**Comment by Reach2N** [comment]
You can bypass this by clicking on more info and "run anyway".

**Comment by maraoz** [comment]
@Reach2N yeah I know. I'm reporting because the team may want to figure out a way to remove that screen somehow, as it might discourage people from installing

**Comment by Reach2N** [comment]
They've tried running VirusTotal.
https://www.virustotal.com/gui/file/464c9c1b273dc2e19d9f54ca214b95018e41a17d07425109d1c96d8212b54c50/detection

**Comment by kuruk-mm** [comment]
> @Reach2N yeah I know. I'm reporting because the team may want to figure out a way to remove that screen somehow, as it might discourage people from installing

![image](https://user-images.githubusercontent.com/12563266/156478818-4b8947a7-d086-4c67-9ce7-901337dfb7e2.png)

The application is already signed by a Certified Authority (ssl.com) but Windows SmartScreen needs massive adoption of the application to stop showing this alert. If you want to double-check its a trusted build, check the certificates by right-clicking on the installer > Properties > Digital Signatures
