### ISSUE TITLE
Add Log out option

### ISSUE THREAD

**Issue by Reach2N** [decentraland/explorer-desktop#137]
### What happened?

Whenever I try to switch accounts from one to another, I have to disable them through wallet connect.

### Steps to reproduce

I'm very new to GitHub and I really don't know how to request this.

### Operating System

Windows 10

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz

### GPU

NVIDIA GeForce 820M 1990MB

### RAM

3979MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-7e33653

### Realm

DG

### NameTag

Tnaot#96bd

**Comment by olavra** [comment]
Hi @Reach2N !

There is a log out option already. You need to go to the start menu, click on your profile and the option will be at the bottom of the pop-up.

![image](https://user-images.githubusercontent.com/41490935/156564671-4ed19b62-955a-469c-8ebc-f51bf5b64e93.png)
