### ISSUE TITLE
The Desktop app crashes and private message still doesn't work

### ISSUE THREAD

**Issue by acrosscoder** [decentraland/explorer-desktop#139]
### What happened?

The Desktop version also crashes and private message still doesn't work
and sometimes its laggy
![Screenshot 2022-03-03 233448](https://user-images.githubusercontent.com/39716656/156598213-bd612ec4-caf8-4f1a-bf12-1195866c9745.png)

![image](https://user-images.githubusercontent.com/39716656/156598378-30d4b35a-6242-493a-b03f-e7a53be2e116.png)

it's

### Steps to reproduce

Occurs when teleporting to another place with a crowded area or loading a huge build

### Operating System

Windows 10  (10.0.19042) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 3 2200G with Radeon Vega Graphics 

### GPU

NVIDIA GeForce GT 710 2007MB

### RAM

8140MB

### Kernel Version

1.0.0-1928584197.commit-b86632b

### Unity Version

desktop-main.commit-80529f2

### Realm

dg

### NameTag

jimsedric#e582

**Comment by pravusjif** [comment]
Thanks for reporting, we'll be tracking this crash at https://github.com/decentraland/explorer-desktop/issues/179
