### ISSUE TITLE
30 FPS Limit probably don't work

### ISSUE THREAD

**Issue by Stefanelll** [decentraland/explorer-desktop#142]
### What happened?

Hi!
The 30 fps limit isn't supposed to not let me have more than 30fps?
I have that option activated and i'm on 80fps, on 2k with preset on 59Hz

### Steps to reproduce

Just check the 30 FPS Limit in Settings :)

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3600X 6-Core Processor 

### GPU

NVIDIA GeForce RTX 3060 Ti 8050MB

### RAM

16310MB

### Kernel Version

1.0.0-1928584197.commit-b86632b

### Unity Version

desktop-main.commit-80529f2

### Realm

dg

### NameTag

Iani#9585

**Comment by Stefanelll** [comment]
i teleported on -5, 50 and i have 200 fps with 30 FPS Limit checked :)))

and one more problem, not with application but in general, when you type to teleport in chat and put '-' the chat is still opened but not checked, like you need to press Enter again to open the chat, click on chat before you type again to not delete the text before and than continue with your teleport coords.

**Comment by Stefanelll** [comment]
Sign Out button crashed my Decentraland Application

**Comment by Stefanelll** [comment]
> Sign Out button crashed my Decentraland Application

Everytime when i press Sign Out the application is crashing, I need to go to Task Manager to End task

**Comment by Stefanelll** [comment]
> Author

Exit button does the same thing, crash the Application

**Comment by kuruk-mm** [comment]
Duplicated by https://github.com/decentraland/explorer-desktop/issues/110

Please, check the issues already created. The majority of the comments that you wrote are already made.
