### ISSUE TITLE
Floating

### ISSUE THREAD

**Issue by FrankG100** [decentraland/explorer-desktop#145]
### What happened?

Any/everytime i am walkking up any kind of stairs or hills my character starts to float and makes the experience very clunky

### Steps to reproduce

reposition physics within how your character reacts to the environment to make you more sucked in and have a more real feeling.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 7 3700X 8-Core Processor 

### GPU

NVIDIA GeForce RTX 3070 8043MB

### RAM

32717MB

### Kernel Version

1.0.0-1928584197.commit-b86632b

### Unity Version

desktop-main.commit-4e9d7b9

### Realm

dg

### NameTag

Frank#1f3a

**Comment by pravusjif** [comment]
This problem will be solved when this issue is tackled: https://github.com/decentraland/explorer-desktop/issues/161
