### ISSUE TITLE
screen ratio issue

### ISSUE THREAD

**Issue by Scoopsy** [decentraland/explorer-desktop#147]
### What happened?

When opening the client the resolution is 1(w):1.5(L) so when i open the menu with I i cant see the options to get into graphics options to change this as i cant see it due to it being hidden under other things as a result of the resolution

### Steps to reproduce

open client with 2 screens set out one above the other
![image](https://user-images.githubusercontent.com/67916013/156861968-ae7ea0de-395f-4550-a08d-56b7ef10df77.png)

### Operating System

Windows 11  64bit

### Wallet

None, played as guest

### CPU

AMD Ryzen Threadripper PRO 3995WX 64-Cores 

### GPU

NVIDIA GeForce RTX 3080 Ti 12108MB x2

### RAM

261969MB

### Kernel Version

1.0.0-1928584197.commit-b86632b

### Unity Version

desktop-main.commit-4e9d7b9

### Realm

dg

### NameTag

fdgsf#74d8

**Comment by Reach2N** [comment]
Click the "P" button on your keyboard when you're in-game.

**Comment by Scoopsy** [comment]
> 

yes i understand this is where it is but the options i need are off the screen due to this resolution it gave me to start with

**Comment by pravusjif** [comment]
this PR that's been recently merged solves this problem.
https://github.com/decentraland/explorer-desktop/pull/162
