### ISSUE TITLE
Decentraland not responding

### ISSUE THREAD

**Issue by Reach2N** [decentraland/explorer-desktop#148]
### What happened?

The app is freezing/not responding and slowing down my entire PC and not using the entire resources.

### Steps to reproduce

After teleporting to the casino, this happens.

### Operating System

Windows 10

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz

### GPU

NVIDIA GeForce 820M 1990MB

### RAM

3979MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-7e33653

### Realm

DG

### NameTag

Tnaot#96bd

**Comment by pravusjif** [comment]
We are tracking those crashes at https://github.com/decentraland/explorer-desktop/issues/179
