### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by westtek126** [decentraland/explorer-desktop#150]
### What happened?

I was in wonderzone and out of no where the app chrashed i dont know if it is because i dont have GPU but the game runs fine without the GPU

### Steps to reproduce

.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz

### GPU

Intel(R) UHD Graphics 630 8082MB

### RAM

16165MB

### Kernel Version

1.0.0-1928584197.commit-b86632b

### Unity Version

desktop-main.commit-4e9d7b9

### Realm

dg

### NameTag

WestTek#cc53

**Comment by Reach2N** [comment]
Your device have iGPU which basically can run decentraland fine. Lower the setting might help especially for iGPU. https://youtu.be/LMEH6TJbzE8

**Comment by pravusjif** [comment]
We'll be tracking this crash at https://github.com/decentraland/explorer-desktop/issues/179
