### ISSUE TITLE
Mining bug

### ISSUE THREAD

**Issue by Funny234-lab** [decentraland/explorer-desktop#153]
### What happened?

Sometimes when u dont have time to mine meteor it dissapears . But the pickaxe mining and the loot shows after meteor gone.

### Steps to reproduce

I tink you should add more time to meteor on the ground :)

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz

### GPU

NVIDIA GeForce GTX 960 4053MB

### RAM

20442MB

### Kernel Version

1.0.0-1928584197.commit-b86632b

### Unity Version

desktop-main.commit-4e9d7b9

### Realm

artemis

### NameTag

Funniokas#df2b

**Comment by Reach2N** [comment]
It's not related to decentraland client, it's about Wonderzone's Wondermine. Those questions can be ask here https://discord.wonderzone.io
