### ISSUE TITLE
App Crashing - Command Failed

### ISSUE THREAD

**Issue by Code-Jefe** [decentraland/explorer-desktop#156]
### What happened?

I have been experiencing some random, but somewhat frequent game crashes ever since using the app for about 2 weeks now. I usually am just standing around, either waiting for meteors to fall in Wondermine or collecting pool balls for being AFK in 8 Meta Balls, when the crash occurs. For reference, here is the error I was able to copy from the post crash screen and it appears to be the exact same error every time.

Error: Command failed: "C:\Users\hanth\AppData\Roaming\explorer-desktop-launcher\renderer\main\unity-renderer-windows.exe" --browser false --port 7666

After receiving this error the last two times, I noticed that my DCL app prompted to me log in with the WalletConnect QR code again. This was not occurring about a week or two ago IIRC, even though I was receiving the same error. Once I reconnect my Metamask mobile wallet, the app seems to play just fine for at least a little.

### Steps to reproduce

Unfortunately I cannot reproduce this issue with any certainty. However, you can try standing around in either Wondermine or 8 Meta Balls game area for about 24 hours AFK and it should occur. I usually do move at least a little bit to get closer to the center of each game area before going AFK.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

### GPU

NVIDIA GeForce RTX 2070 SUPER 8012MB

### RAM

32681MB

### Kernel Version

1.0.0-1959721167.commit-e8e7260

### Unity Version

desktop-main.commit-2692e39

### Realm

dg

### NameTag

Jefe#3809

**Comment by Reach2N** [comment]
I don't really know about the crashing, but I do know is you need to connect your wallet through WalletConnect every time you open a client due to security purposes. 

Extra:
if developers here and read this message I'd like to request a Metamask extension to the client. Thanks

**Comment by pravusjif** [comment]
Thanks for all the info, we'll be tracking this crash at https://github.com/decentraland/explorer-desktop/issues/179

> Extra: if developers here and read this message I'd like to request a Metamask extension to the client. Thanks
That subject is being talked about in the Product department, we still don't have an update on that, but since most people ask for it I think we may implement something for metamask, but can't promise it right now.
