### ISSUE TITLE
i didn t receive my wearable

### ISSUE THREAD

**Issue by Flightspirit** [decentraland/explorer-desktop#157]
### What happened?

i used decentraland on google
yesterday i begin use your beta program to have better graphism
and i have lot of problems

1/ i use metamask on google and on the appli......but the appli didn t recognize my lvl on google and i had to play back from the beginning

2/ i ve baught a wearable from google on the wilderness shop  ( santa costume wearable nft)
because i couldn t use it on the appli, i baught it again on the wilderness shop (playing on the appli where i paid 1200 wilderness coins).........but i neither receive it

### Steps to reproduce

no step , i baught a nft on wilderness shop....neither receive it

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz

### GPU

NVIDIA GeForce GTX 1050 Ti 4018MB

### RAM

8079MB

### Kernel Version

1.0.0-1959721167.commit-e8e7260

### Unity Version

desktop-main.commit-2692e39

### Realm

dg

### NameTag

Flightspirit#1229

**Comment by Reach2N** [comment]
This isn't related to Decentraland client. Please close this issue.

**Comment by pravusjif** [comment]
If you have an NFT wearable in your wallet and you see it in the browser client, after loading your wallet in a mobile wallet app like TrustWallet or Metamask Mobile, you can connect with Wallet Connect to the desktop client and you will see your wearable there.
