### ISSUE TITLE
bug on training 1-21 golfcraft map

### ISSUE THREAD

**Issue by Flightspirit** [decentraland/explorer-desktop#158]
### What happened?

on this map , you have a sort of lift
the problem is that when you put your ball on , it passes through the lift  and don t do up with the lift........and we re blocked for 8 mn , waiting the training finish

### Steps to reproduce

just place your ball on the lift

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz

### GPU

NVIDIA GeForce GTX 1050 Ti 4018MB

### RAM

8079MB

### Kernel Version

1.0.0-1959721167.commit-e8e7260

### Unity Version

desktop-main.commit-2692e39

### Realm

dg

### NameTag

Flightspirit#1229

**Comment by Reach2N** [comment]
This isn't related to Decentraland client. Please close this issue.
