### ISSUE TITLE
Black texture reflection

### ISSUE THREAD

**Issue by Reach2N** [decentraland/explorer-desktop#163]
### What happened?

black reflection from nowhere and some certain area.

### Steps to reproduce

none

### Operating System

W10

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz

### GPU

NVIDIA GeForce 820M 1990MB

### RAM

3979MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-7e33653

### Realm

DG

### NameTag

Tnaot#96bd

**Comment by pravusjif** [comment]
thanks for reporting, that bug is being tracked at https://github.com/decentraland/explorer-desktop/issues/119 and its fix is on the way
