### ISSUE TITLE
Timed out loading session

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/explorer-desktop#166]
![image](https://user-images.githubusercontent.com/12563266/158242031-54803681-ca8c-47d2-a19a-bf94cca2ba4c.png)

This happens after opening the Desktop Client, and it doesn't connect with the Launcher for more than 10 seconds for some reason.

I think one of the following problems are happening:
- The launcher crashes after opening the Desktop Client
- Firewall rules that don't allow the communication between Desktop Client and Launcher

**Comment by pravusjif** [comment]
this bug is fixed and has been tracked at https://github.com/decentraland/explorer-desktop/issues/170

**Comment by cags9607** [comment]
I'm still having this bug.
