### ISSUE TITLE
Error: The avatar could not be loaded correctly

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/explorer-desktop#168]
![image](https://user-images.githubusercontent.com/12563266/158284050-c354944e-66ff-491d-baac-26a29f961082.png)

We need more information about this issue

**Comment by Reach2N** [comment]
Same

**Comment by dwinbur** [comment]
same problem

**Comment by Reach2N** [comment]
oh it fixed

**Comment by pravusjif** [comment]
this bug is fixed and has been tracked at https://github.com/decentraland/explorer-desktop/issues/170
