### ISSUE TITLE
DCL Desktop does not warn Unity Dependency

### ISSUE THREAD

**Issue by thatcampbellkid** [decentraland/explorer-desktop#177]
### What happened?

Downloaded DCL Desktop and tried starting as guest several times. I downloaded Unity on an unrelated note and made the connection it may be a dependency, now it loads correctly.

DCL Desktop took me all the way up to 99% loading the world before just terminating with a generic error.

### Steps to reproduce

Download DCL Desktop, start a session without having Unity installed.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

None, played as guest

### CPU

Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

### GPU

Intel(R) UHD Graphics 620 8135MB

### RAM

16270MB

### Kernel Version

1.0.0-1990570041.commit-c77c4c3

### Unity Version

desktop-main.commit-cedda56

### Realm

unicorn

### NameTag

dude#a178

**Comment by pravusjif** [comment]
The desktop client doesn't have any dependency. You probably were suffering from this issue we had a couple of days ago, now it's fixed: https://github.com/decentraland/explorer-desktop/issues/170
