### ISSUE TITLE
Bug made me lose chips

### ISSUE THREAD

**Issue by geritootero** [decentraland/explorer-desktop#183]
### What happened?

I was playing and raised in the river. I had Full house of 89, the other person folded so i was supossed to win 400 chips but instead of that I lose them, it kind of frezze for a second and when it resumed I was 400 chips down. You can see in the images that my chip count does not add uo with the chips won and available chips so its clearly a bug.
![d49a15d4-b136-4bc2-8bb6-6d9d66d3ee34](https://user-images.githubusercontent.com/102125502/159392359-44ea1f7d-bb06-4f91-9f49-cc98f35d23e4.jpg)
![138c6b34-2eaf-4c0b-8e7b-2f518623159f](https://user-images.githubusercontent.com/102125502/159392375-a3562dcf-b11d-4b84-8e2c-9225a2f710e2.jpg)
![66004b7e-e22c-496d-84b8-bc8b2db07909](https://user-images.githubusercontent.com/102125502/159392387-150b236c-2b40-481d-8189-9bea9cc6525f.jpg)

 

### Steps to reproduce

I was playing and raised in the river. I had Full house of 89, the other person folded so i was supossed to win 400 chips but instead of that I lose them, it kind of frezze for a second and when it resumed I was 400 chips down. You can see in the images that my chip count does not add uo with the chips won and available chips so its clearly a bug.
![d49a15d4-b136-4bc2-8bb6-6d9d66d3ee34](https://user-images.githubusercontent.com/102125502/159392359-44ea1f7d-bb06-4f91-9f49-cc98f35d23e4.jpg)
![138c6b34-2eaf-4c0b-8e7b-2f518623159f](https://user-images.githubusercontent.com/102125502/159392375-a3562dcf-b11d-4b84-8e2c-9225a2f710e2.jpg)
![66004b7e-e22c-496d-84b8-bc8b2db07909](https://user-images.githubusercontent.com/102125502/159392387-150b236c-2b40-481d-8189-9bea9cc6525f.jpg)

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 

### GPU

AMD Radeon(TM) Vega 8 Graphics 3041MB

### RAM

6082MB

### Kernel Version

1.0.0-2017584015.commit-f1ef137

### Unity Version

desktop-main.commit-ad56db4

### Realm

dg

### NameTag

geromino#eb16

**Comment by pravusjif** [comment]
This issue should be reported to [Decentral Games](https://decentral.games/), they own and implement that scene, the bug has nothing to do with the Decentraland client.
