### ISSUE TITLE
Issue when trying to access fashion event...

### ISSUE THREAD

**Issue by Juzzydecentraland** [decentraland/explorer-desktop#187]
### What happened?

![Screenshot 2022-03-26 155529](https://user-images.githubusercontent.com/96121477/160247448-18961279-0b25-4186-8bb8-2a28ba05fe9a.png)

### Steps to reproduce

Open Client - login a guest - go to events page, jump into one of the fashion events. 
![Screenshot 2022-03-26 155529](https://user-images.githubusercontent.com/96121477/160247401-84bca848-ccbc-49c2-8e0c-317530fc4428.png)
![Screenshot 2022-03-26 155529](https://user-images.githubusercontent.com/96121477/160247405-fe32a236-7bef-4b56-887f-d08cca3b20de.png)
![Screenshot 2022-03-26 155529](https://user-images.githubusercontent.com/96121477/160247411-9894aec3-ce38-42c6-a27f-b3a63ae45b30.png)

### Operating System

Chrome, Windows 11

### Wallet

None, played as guest

### CPU

i7

### GPU

NVIDIA 

### RAM

32GB

### Kernel Version

1.0.0 -2036429826.commit-e96a984

### Unity Version

Latest

### Realm

Nifty passage

### NameTag

juzzy007

**Comment by pravusjif** [comment]
Those crashes are being tracked at https://github.com/decentraland/explorer-desktop/issues/179
