### ISSUE TITLE
8 MetaBalls

### ISSUE THREAD

**Issue by Adimir2020** [decentraland/explorer-desktop#205]
### What happened?

8 MetaBalls - after leaving the table, the "power" scale remains. The scale disappears after re-entering the world. 
I hope I helped you)
![Снимок экрана (133)](https://user-images.githubusercontent.com/67873287/161820092-fd44ef7c-9ec3-49ab-a645-8931bf23a84e.png)

### Steps to reproduce

Try to rewrite the code responsible for interacting with the table

### Operating System

Windows 10  (10.0.19041) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 1400 Quad-Core Processor 

### GPU

NVIDIA GeForce GTX 1050 Ti 4018MB

### RAM

16336MB

### Kernel Version

1.0.0-2071407489.commit-9b51f8e

### Unity Version

desktop-main.commit-a87c45d

### Realm

unicorn

### NameTag

Neo#6f96

**Comment by eordano** [comment]
This is an issue with https://decentral.games/ and not with Decentraland. Please report that to the owners of the "8 Metaballs" scene; this repository only contains the reference implementation of the Decentraland Protocol
