### ISSUE TITLE
Video delivery not happening in the Desktop Beta

### ISSUE THREAD

**Issue by krcnow** [decentraland/explorer-desktop#208]
### What happened?

The video play is not happening whereas it works properly in the browser.

### Steps to reproduce

You can visit the Filmrare movie screening event and walk into Theater 3 using the desktop app.

![image](https://user-images.githubusercontent.com/37628523/162274168-235ae247-3ed5-40aa-bdc9-0c9381940baa.png)

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

### GPU

NVIDIA GeForce MX150 4027MB

### RAM

16284MB

### Kernel Version

1.0.0-2098154396.commit-22a0cf9

### Unity Version

desktop-main.commit-a87c45d

### Realm

dg

### NameTag

Mark#c388

**Comment by kuruk-mm** [comment]
Confirmed

Position: 2,55
Video url: https://stream.mux.com/7tiiH48UA3JicTrzYmW5h8cqvvOzcCLGLAr2uPeGT00Q.m3u8

**Comment by TheShoes** [comment]
Video stream did not show at metazoo Friday nigh. 
pos 110,-23
the feed has ended now but the link to the feed was 
https://emedia.dclconnect.io:5443/metazoo/streams/865964267200403541562902.m3u8
Here is info on the feed i was able to pull from VLC player
<img width="393" alt="video file" src="https://user-images.githubusercontent.com/7997186/163678639-d00d0fcd-b206-48b3-9b14-ad8c2d4a7cc1.png">

**Comment by TheShoes** [comment]
Is there any update on the streaming issue?   Can confirm it is still not working on -17,-122,  on second floor

**Comment by avf456** [comment]
same issue is happening on -22,37 and that video is local to the scene.

**Comment by Jusdem** [comment]
The Unity engine only supports file-based video which is not good for hosting large events (doesn't scale): https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html

We need to implement a Unity HLS player into Decentraland desktop client, however most of these cost money and are licensed. Example: https://nexplayersdk.com/unity-player-sdk/

How does one suggest we proceed?

**Comment by kuruk-mm** [comment]
> The Unity engine only supports file-based video which is not good for hosting large events (doesn't scale): https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html
> 
> 
> 
> We need to implement a Unity HLS player into Decentraland desktop client, however most of these cost money and are licensed. Example: https://nexplayersdk.com/unity-player-sdk/
> 
> 
> 
> How does one suggest we proceed?

The explorer-desktop is not using the Unity implementation.

It's using a native implementation that dependa on FFmpeg. Here the code: https://github.com/decentraland/DCLVideoPlayer

And we support HLS. Sometimes the problem itself is not HLS. It's the format of the video/audio.

Chrome uses FFMpeg too. But they have more supportes formats than FFmpeg. So it's difficult to have the same compatibility as Chrome.

I will review what is happening. Please. Send me every HLS video that you have so I can review and test

**Comment by pravusjif** [comment]
Hello, we'll be tracking all Video/Audio playing problems in the desktop client centralized in this other issue: 
- https://github.com/decentraland/explorer-desktop/issues/322

I'm marking this issue as duplicate and closing it, sorry for the inconvenience.
