### ISSUE TITLE
Replace the timeout popup with a more descriptive one

### ISSUE THREAD

**Issue by Kinerius** [decentraland/explorer-desktop#216]
The current timeout popup seems a bit off and it gives the feel of a "soft crash" while the world is still being loaded in the background.
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/96f088c1-59a2-4902-9577-966f2914bef7)

This is the proposal for a new popup. [Figma](https://www.figma.com/file/akmeRX6da0lnNuJuN50eMC/Loading-%26-ErrorsScreens?node-id=1461%3A2)
<img width="1108" alt="Screen Shot 2022-04-11 at 14 09 53" src="https://user-images.githubusercontent.com/51088292/162793510-71a4bebc-672b-4fe8-a807-6c34d8857028.png">

**Comment by JorgeDecentraland** [comment]
@RominaMarchetti could you attach the final design for this issue, please?

**Comment by RominaMarchetti** [comment]
@JorgeDecentraland the design is attached above. I've included it in Pato's comment :)
