### ISSUE TITLE
tables keep erroring out and i lost a bunch of chips

### ISSUE THREAD

**Issue by twelker10** [decentraland/explorer-desktop#227]
### What happened?

was playing a hand at the dext lounge at approx 2:00. The table glitched out and backed everyone out off the table in the middle of the hand. Ihad over 500 chips alone on the pot with quad kings with kk in my hand.

### Steps to reproduce

unable to because the game glitched and backed out off my table in the middle of a hand

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD FX(tm)-6300 Six-Core Processor 

### GPU

NVIDIA GeForce RTX 3060 12143MB

### RAM

20435MB

### Kernel Version

1.0.0-2141827118.commit-450c363

### Unity Version

desktop-main.commit-64822b7

### Realm

dg

### NameTag

Kryone420#24d1

**Comment by pravusjif** [comment]
This is a problem with the scene, not the Decentraland Client
