### ISSUE TITLE
Cannot seem to sign Metamask wallet in the PC version

### ISSUE THREAD

**Issue by MommaCanna** [decentraland/explorer-desktop#228]
### What happened?

![image](https://user-images.githubusercontent.com/103216969/162802263-86628db3-8450-4bfc-9e40-1365b3f7a45e.png)
 
When I try to sign anything using Metamask in game, it never loads

### Steps to reproduce

Try to sign Metamask wallet to connect while in PC game version

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD FX(tm)-6350 Six-Core Processor 

### GPU

NVIDIA GeForce GTX 1050 Ti 4018MB

### RAM

16341MB

### Kernel Version

1.0.0-2149292527.commit-b323b2d

### Unity Version

desktop-main.commit-64822b7

### Realm

dg

### NameTag

MommaCanna#af3a

**Comment by pravusjif** [comment]
This issue was fixed on Metamask side apparently
