### ISSUE TITLE
bug defect on my winning hand

### ISSUE THREAD

**Issue by twelker10** [decentraland/explorer-desktop#231]
### What happened?

i won a hand for 800 chips. the next hand half way though it deleted them and gave me -70 chips. WTF!!!

### Steps to reproduce

i dont know you tell me how to reproduce it. its your game that glitched out and stole my chips

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD FX(tm)-6300 Six-Core Processor 

### GPU

NVIDIA GeForce RTX 3060 12143MB

### RAM

20435MB

### Kernel Version

1.0.0-2149292527.commit-b323b2d

### Unity Version

desktop-main.commit-64822b7

### Realm

dg

### NameTag

Kryone420#24d1

**Comment by pravusjif** [comment]
This is a problem with the scene, not the Decentraland Client
