### ISSUE TITLE
Aspect ratio issues

### ISSUE THREAD

**Issue by Mr-Grogan** [decentraland/explorer-desktop#232]
### What happened?

Still having problems with aspect ratio and screen size.  
Full Screen Borderless and Windowed are Portrait.  
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/100754813/162918722-fb986887-21a8-4821-b23f-93b2e7f2669d.png">

Full Screen is stretched to fit screen.
![Uploading image.png…]()

### Steps to reproduce

![image](https://user-images.githubusercontent.com/100754813/162919358-65894969-a16a-42a8-9e1f-f53beb0a1781.png)

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz

### GPU

NVIDIA Quadro T1000 3962MB

### RAM

16160MB

### Kernel Version

1.0.0-2149292527.commit-b323b2d

### Unity Version

desktop-main.commit-64822b7

### Realm

dg

### NameTag

Grogan#ef0a

**Comment by pravusjif** [comment]
Try pressing CTRL+F11 to force the client to go full screen, that's been added when we updated the client with the latest fix regarding this issue

**Comment by Kinerius** [comment]
I've tested disabling unsupported aspect ratios and tweaking some unity settings to no avail, Another user has this problem and it "sometimes happens" so its random, it also could be related to having multiple displays.

**Comment by Kinerius** [comment]
https://github.com/decentraland/explorer-desktop/pull/265

This PR might fix the problem, I will update this issue after its released and we are certain that its not happening anymore

**Comment by Mr-Grogan** [comment]
> I've tested disabling unsupported aspect ratios and tweaking some unity settings to no avail, Another user has this problem and it "sometimes happens" so its random, it also could be related to having multiple displays.

Single display here, running single display.  4K monitor via Display Port cable.  Consistent, not sometimes for me.

**Comment by Mr-Grogan** [comment]
> #265
> 
> This PR might fix the problem, I will update this issue after its released and we are certain that its not happening anymore

Per comment on #265 - no change from what I tried.

**Comment by Kinerius** [comment]
Hey, @Mr-Grogan, were you able to test https://github.com/decentraland/explorer-desktop/pull/265 correctly?

**Comment by Kinerius** [comment]
After some investigation we determined that this is a unity bug caused by using different displays, we are going to revise this issue again in the future once we update our unity version.

**Comment by Kinerius** [comment]
Unity has some problems detecting the main display and there are some fixes to check out on unity 2022 and 2021.3. For more info check this thread https://forum.unity.com/threads/how-to-get-game-build-to-run-on-main-display.1273394/#post-8204898

There's a script on that thread that forces the game to go back to the main display, we can use that until we update unity to 2021.3 

For now, Decentraland has to be opened on the Main Display only to avoid resolution issues.
