### ISSUE TITLE
Metamask

### ISSUE THREAD

**Issue by Gotsauss** [decentraland/explorer-desktop#238]
### What happened?

There is no metamask. Everything is running very smooth on the desktop client on my PC, but there is no option to use Metamask. 

### Steps to reproduce

Starts from the very beginning.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

### GPU

NVIDIA GeForce GTX 1650 3962MB

### RAM

16253MB

### Kernel Version

1.0.0-2171767659.commit-6258301

### Unity Version

desktop-main.commit-64822b7

### Realm

unicorn

### NameTag

Test#3337 but my usual tag is Gotsauss#05ff

**Comment by pravusjif** [comment]
You can use Metamask Mobile and connect using the QR (look for the Wallet-Connect option in the mobile app).
Right now there is no support for **browser metamask extension** (that's what you are asking for), although the Product department is evaluating approving that implementation.
