### ISSUE TITLE
Debug crash in RC

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#241]
I Experienced a crash at `NETWORK=ropsten&position=54,-70`, at the end of this usual Rc test run:

https://user-images.githubusercontent.com/1031741/163814937-1d7d7fda-4483-4d9a-872e-5d7fd1760a56.mp4

[Player.log](https://github.com/decentraland/explorer-desktop/files/8506191/Player.log)

**Comment by kuruk-mm** [comment]
I tried everything you did for 30 minutes, and I couldn't reproduce it.

**Comment by pravusjif** [comment]
Apparently the trick is to have the Scene Load Radius setting in "6", and I'm being able to reproduce this even in the web client, it looks like Kernel has a memory crash and disconnects itself from the renderer

![chrome_vD6WnxVVK3.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/7327b018-5c84-4ce3-9c44-b0a286a4dcbf)

When reproducing the crash from the web client, we can see some nullref exceptions, that are most likely from the nullref that can be seen sometimes in Unity Editor at
- https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs#L1813
- any `.mesh` usage at `ConstructUnityMesh()` at https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs#L1949

But reproducing the crash from the Editor also shows that even though those errors sometimes appear (in unity-side) the Kernel disconnects itself with its own memory crash at another point in time (thus [provoking the `Application.Quit()` of the desktop client renderer](https://github.com/decentraland/explorer-desktop/blob/main/unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs#L116)), so I'd say those nullref are not the cause of kkernel's "memory crash".

I'll continue the investigation doing a commit hunting with kernel versions to see if we had this issue for a long time or not, but the trick appears to be having the Scene Load Radius 6

**Comment by pravusjif** [comment]
I confirmed that this issue is already happening in the production build of the desktop client and also in the web client, and since it's a Kernel problem I created the pertinent issue in their repo: https://github.com/decentraland/kernel/issues/275
