### ISSUE TITLE
Crash at -40, 124

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#248]
Possible video crash

![desktop_crash_-40,124](https://user-images.githubusercontent.com/1031741/164368827-9fcca444-a212-4f35-bf85-705dde96a563.png)

[desktop_crash_-40,124_Player.log](https://github.com/decentraland/explorer-desktop/files/8527103/desktop_crash_-40.124_Player.log)

**Comment by davidejensen** [comment]
I was trying to reproduce this in mac, I've been walking around the scene and it doesn't crash but I've realised that the scene that appears in the screenshot is no longer there, is there a different place where this was happening? Otherwise I think we have no way of reproducing it anymore

**Comment by pravusjif** [comment]
the only relevant errors that I see in that player log are some errors regarding the broken 'settings controller' prefab, those problems should be fixed at
https://github.com/decentraland/explorer-desktop/pull/300
https://github.com/decentraland/unity-renderer/pull/2316

Hopefully those fixes will solve this crash.

Since we cannot reproduce it anymore because that scene is not there anymore, we'll be closing the issue.
