### ISSUE TITLE
Ball and stick in the air

### ISSUE THREAD

**Issue by IggyCifu** [decentraland/explorer-desktop#251]
### What happened?

While playing, the ball just stood in the air, no way to play.

### Steps to reproduce

Ball to elevator - ball does not stand in elevator, it stays in the air.

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

### GPU

NVIDIA GeForce GTX 1650 3962MB

### RAM

16235MB

### Kernel Version

1.0.0-2189800740.commit-1ab8e83

### Unity Version

desktop-main.commit-64822b7

### Realm

dg

### NameTag

IggyRock#0d13

**Comment by pravusjif** [comment]
In which scene did this happen? It looks like a problem with the scene's code not the client

**Comment by IggyCifu** [comment]
Hi,
Attached a pic of the scene I am stuck in.
Its a nice game.
Best,
Iggy

**Comment by JorgeDecentraland** [comment]
Issue in the scene
