### ISSUE TITLE
TABLE AUTOMATICALLY KICKED ME

### ISSUE THREAD

**Issue by boypuso** [decentraland/explorer-desktop#252]
### What happened?

TABLE AUTOMATICALLY KICKED ME

ALL IN THE PRE-FLOP AND THEN SUDDENLY TABLE KICKED ME.

NOW I LOST A LOT OF CHIPS BECAUSE OF THAT. 

![image](https://user-images.githubusercontent.com/104166687/164536687-b0560d40-7054-46cb-b848-87c0a2b38520.png)

### Steps to reproduce

Fix the bug 

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3600 6-Core Processor 

### GPU

NVIDIA GeForce GTX 1650 3961MB

### RAM

16294MB

### Kernel Version

1.0.0-2189800740.commit-1ab8e83

### Unity Version

desktop-main.commit-7b08a86

### Realm

dg

### NameTag

marites#c079

**Comment by pravusjif** [comment]
This is a problem with the scene's code, not the client
