### ISSUE TITLE
Chistmas voting unavailable

### ISSUE THREAD

**Issue by IggyCifu** [decentraland/explorer-desktop#253]
### What happened?

Clickin´the link, the webpage does not exist

### Steps to reproduce

At chistmas space, once you click the voting link, the page gives error

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

### GPU

NVIDIA GeForce GTX 1650 3962MB

### RAM

16235MB

### Kernel Version

1.0.0-2189800740.commit-1ab8e83

### Unity Version

desktop-main.commit-7b08a86

### Realm

dg

### NameTag

IggyRock#0d13

**Comment by JorgeDecentraland** [comment]
Scene issue
