### ISSUE TITLE
Half visible on a 4K display

### ISSUE THREAD

**Issue by SongShawn** [decentraland/explorer-desktop#255]
### What happened?

1. Only half of the screen is visible on a 4K display
2. The setting screen can only be seen on the left side of the 4K display, and the resolution cannot be set  
3. 
![image](https://user-images.githubusercontent.com/12530965/164891017-226f7314-4e65-4e15-8951-8cbab94b1292.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/12530965/164891011-0a272cf2-799f-49f2-aa1c-9cecfd1dddd1.png)

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

### GPU

NVIDIA GeForce GTX 1070 8081MB

### RAM

16332MB

### Kernel Version

1.0.0-2189800740.commit-1ab8e83

### Unity Version

desktop-main.commit-7b08a86

### Realm

heimdallr

### NameTag

SSSSSSSS#25b7

**Comment by kuruk-mm** [comment]
Duplicated https://github.com/decentraland/explorer-desktop/issues/232
