### ISSUE TITLE
Streaming not working at -118,120

### ISSUE THREAD

**Issue by gabrielmellace1** [decentraland/explorer-desktop#279]
### What happened?

Streaming is working on the browser version but it doesnt work on the desktop version

### Steps to reproduce

Go to -118,120 on desktop version and then on browser version

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz

### GPU

AMD Radeon RX 5600 XT 6102MB

### RAM

65452MB

### Kernel Version

1.0.0-2227136955.commit-c4944ec

### Unity Version

desktop-main.commit-7b08a86

### Realm

dg

### NameTag

GabeDG

**Comment by pravusjif** [comment]
Hello, we'll be tracking all Video/Audio playing problems in the desktop client centralized in this other issue: 
- https://github.com/decentraland/explorer-desktop/issues/322

I'm marking this issue as duplicate and closing it, sorry for the inconveniences.
