### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SGasita** [decentraland/explorer-desktop#289]
### What happened?

I got all in and won with full house of J-s over 10-s and when I was supposed to get chips i have got kicked from table received 
-chips and 25 min ban
![image](https://user-images.githubusercontent.com/104946226/166837578-8d6b8d04-6bc0-49c2-8be7-807e10887d64.png)

### Steps to reproduce

I don't know

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

### GPU

NVIDIA GeForce GTX 1060 3GB 2988MB

### RAM

16327MB

### Kernel Version

1.0.0-2258376128.commit-f035f09

### Unity Version

desktop-main.commit-3062949

### Realm

dg

### NameTag

Gasita#b4fd

**Comment by pravusjif** [comment]
This is relate to the scene's code (DGs Ice Poker casino), not Decentraland's desktop client.
