### ISSUE TITLE
Better error reporting message after timeout from the Kernel<->Renderer connection

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/explorer-desktop#319]
We have the following error message:

![image](https://user-images.githubusercontent.com/12563266/172000051-cb8810d9-80a8-4af6-b107-69e1375c0453.png)

This could happen for 2 reasons.

1. The Kernel<->Renderer connection, never started (it should start after a few seconds the Renderer opens)
2. After the Kernel<->Renderer connects, and the loading takes too long (like more than one minute)

For the first case, after the Kernel<->Renderer connection, the problem could be a Firewall error.
So we should add better messaging, requesting the user to check their Firewall to see if is not blocking the communication between Kernel<->Renderer.

**Comment by bergome** [comment]
I have the same problem
Can someone explain in detail how to fix it?
