### ISSUE TITLE
Report button is not working

### ISSUE THREAD

**Issue by Titan0429** [decentraland/explorer-desktop#332]
### What happened?

I tried to report someone for Vulgar language and racism. But the page opens up to a page that says This typeform has moved to a new address
Hit the button and we'll redirect you to
form.typeform.com
then next page says 
Hey :) This typeform is now closed
It would have been awesome as it was made with Typeform. What’s that?

### Steps to reproduce

report a player in chat+

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

### GPU

NVIDIA GeForce GTX 1660 SUPER 5992MB

### RAM

12195MB

### Kernel Version

1.0.0-2036429826.commit-e96a984

### Unity Version

desktop-main.commit-24f4dfe

### Realm

dg

### NameTag

Titan0429#6908

**Comment by JorgeDecentraland** [comment]
This is the typeform that is not working https://decentralandofficial.typeform.com/to/owLkla?username=${username}

**Comment by JorgeDecentraland** [comment]
The report button has been fixed by adding a new form
