### ISSUE TITLE
Avatar moves alone

### ISSUE THREAD

**Issue by TheFlo2490** [decentraland/explorer-desktop#337]
### What happened?

I played for the first time and my avatar moves without touching the keys. I disconected the keyboard, the mouse and all other external devices. The avatar is still moving. 
I also tried the browser and the desktop version of the game. I also restarted the computer.
Nothing is helping.

### Steps to reproduce

Please send me a solution for this problem. 

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz

### GPU

NVIDIA GeForce GTX 1080 8079MB

### RAM

16338MB

### Kernel Version

1.0.0-2322196163.commit-bfb06e9

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

dg

### NameTag

Donkey#ecf0

**Comment by JorgeDecentraland** [comment]
Closing the issue due to the lack of user's response
