### ISSUE TITLE
Make "Bug Report" button hideable (PC ver)

### ISSUE THREAD

**Issue by gigasraid** [decentraland/explorer-desktop#339]
### What happened?

It's covering a few games' UI hence ruining visibility

### Steps to reproduce

Nothing

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Wallet Connect

### CPU

AMD Ryzen 7 3700X 8-Core Processor 

### GPU

NVIDIA GeForce GTX 1070 8088MB

### RAM

32679MB

### Kernel Version

1.0.0-2503059035.commit-0dd1ae6

### Unity Version

desktop-1.0.387-20220615161653.commit-3df2ab6

**Comment by JorgeDecentraland** [comment]
Issue in scenes
