### ISSUE TITLE
Unable to minimize out of fullscreen

### ISSUE THREAD

**Issue by JonnyFiat** [decentraland/explorer-desktop#349]
### What happened?

I am using the MAC client beta and while in fullscreen, realized that I cannot leave full screen.

### Steps to reproduce

Go into Fullscreen...

### Operating System

Mac OS X 12.4.0

### Wallet

None, played as guest

### CPU

Apple M1

### GPU

Apple M1 5461MB

### RAM

8192MB

### Kernel Version

1.0.0-2570291833.commit-c09e849

### Unity Version

desktop-1.0.416-20220623144956.commit-c9134b0

### Realm

dg

### NameTag

Bekiodish#957e

**Comment by davidejensen** [comment]
Hello @JonnyFiat , could you please be more specific? If you go into the settings panel and in the Graphics sections, do you see the dropdown option to change the window mode? What happens if you switch to `Windowed` instead of fullscreen?
