### ISSUE TITLE
Video Stream just displaying as a white box

### ISSUE THREAD

**Issue by CDeLeon94** [decentraland/explorer-desktop#360]
### What happened?

Unable to watch a video stream

### Steps to reproduce

Joined Metaverse Summit -94,103
On the top floor there are 3 windows to watch a stream, but on the desktop client, nothing shows up. 

Using Firefox to join works. 

### Operating System

Windows 11  (10.0.22622) 64bit

### Wallet

Wallet Connect

### CPU

AMD Ryzen 5 2600 Six-Core Processor 

### GPU

NVIDIA GeForce RTX 3060 Ti 8050MB

### RAM

32693MB

### Kernel Version

1.0.0-2673696742.commit-535b3fa

### Unity Version

desktop-1.0.481-20220714181434.commit-d37208d

### Realm

dg

### NameTag

Walrus#c3f2

**Comment by pravusjif** [comment]
Hello, we'll be tracking all Video/Audio playing problems in the desktop client centralized in this other issue: 
- https://github.com/decentraland/explorer-desktop/issues/322

I'm marking this issue as duplicate and closing it, sorry for the inconvenience.
