### ISSUE TITLE
Golf Boards are blank for me

### ISSUE THREAD

**Issue by atway75** [decentraland/explorer-desktop#362]
### What happened?

i could not interact with the blue boards as they are white without any writings. i can not see any letters so i can not play golf. i tried in all the floors! all the boards are white 

### Steps to reproduce

please advice how to solve this problem

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 

### GPU

AMD Radeon(TM) Vega 8 Graphics 3017MB

### RAM

6035MB

### Kernel Version

1.0.0-2673696742.commit-535b3fa

### Unity Version

desktop-1.0.481-20220714181434.commit-d37208d

### Realm

dg

### NameTag

Aminius#8fe0

**Comment by JorgeDecentraland** [comment]
Closing due to lack of feedback from user
