### ISSUE TITLE
Duplicated coordinates in minimap HUD for some scenes

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#366]
Some scenes instead of showing their scene name, show their coordinates and it looks bugged.

Repro steps:
1. Start at 0,0
2. Go to 100,100
3. Start walking around

![duplicated-coordinates](https://user-images.githubusercontent.com/1031741/181350536-c4e21395-3adb-4e3c-b8ac-85e74d96741e.png)

**Comment by lorux0** [comment]
from the renderer side we are receiving from kernel, the coordinates in the name, on `UpdateMinimapSceneInformation` message:
![Screen Shot 2022-08-01 at 18.18.12.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/b880987a-2662-4bf2-88c1-a0b97c99081c)
