### ISSUE TITLE
Can't verify developer n 

### ISSUE THREAD

**Issue by ACC-minter** [decentraland/explorer-desktop#369]
### What happened?

<img width="252" alt="Screen Shot 2022-08-04 at 11 07 55 AM" src="https://user-images.githubusercontent.com/110628657/182920635-e3ec2fe6-8d20-483e-9736-0781e20d8ae8.png">

### Steps to reproduce

dowloaded from link in email announcing MacOS app for Dentraland
used regular dialog to load .dmg file into apps
launched app 
bombed as shown in attachment

### Operating System

MacOS Monterey 12.5

### Wallet

None, played as guest

### CPU

2 Ghz Quad-Core Intel Core i5

### GPU

unknown

### RAM

16GB

### Kernel Version

unknown

### Unity Version

unknown

### Realm

unknown

### NameTag

acc-minter

**Comment by JorgeDecentraland** [comment]
This is expected behavior.
