### ISSUE TITLE
Investigate scenes not correctly loading on Desktop

### ISSUE THREAD

**Issue by Kinerius** [decentraland/explorer-desktop#386]
A user reported that some scenes don't load on desktop but do on WebGL, this might be related to the usage of GLTF's or it's maybe a request issue.

UPDATE:
More users report this problem happening on their scenes.
Example coordinates: "-20,26", "-19,26", "-20,27", "-19,27", "-29,26", "-24,-9"

**Comment by arisAlexis** [comment]
I had the same issue. The project we made (DCL Steampunk Saloon) had video streaming from a static file which worked in the browser but not in the desktop version.

**Comment by Kinerius** [comment]
@arisAlexis video streaming is a different topic and we are currently working on it, you can check its progress [here](https://github.com/decentraland/unity-renderer/issues/2995) 
This ticket was created because we had some reports of some scenes failing to load some models but we lack information on which scenes.

**Comment by seanellul** [comment]
Hey @Kinerius  

We ran into this problem today with our build on -29,26

Happy to share all necessary information to ensure we can solve this asap.

**Comment by agustincarriso** [comment]
When you try to enter the link you get stuck at 48% 
https://play.decentraland.org/?NETWORK=mainnet&position=-20%2C26&realm=baldr
![Captura de pantalla 2022-10-20 a la(s) 12 03 38](https://user-images.githubusercontent.com/86750198/196986235-6ecbd895-f9b2-46e7-95d3-9a534ddfe7ea.png)

**Comment by agustincarriso** [comment]
Trying to run it locally, get stuck at 0% 
![Captura de pantalla 2022-10-20 a la(s) 12 24 44](https://user-images.githubusercontent.com/86750198/196991183-441fb4a6-0b10-49e8-9f9e-5ae394d6a916.png)

**Comment by seanellul** [comment]
The bug has extended to parcels -24, -9


We are halting all events/launches/builds/client operations in Decentraland until we can get some direction on what is currently happening and where these issues are coming from. 

Updates would be appreciated.

I'm at your disposal to share more information.

**Comment by kuruk-mm** [comment]
> The bug has extended to parcels -24, -9
> 
> We are halting all events/launches/builds/client operations in Decentraland until we can get some direction on what is currently happening and where these issues are coming from.
> 
> Updates would be appreciated.
> 
> I'm at your disposal to share more information, at any time.

Hi Seanny, can you try with the following URL? To check if you are experiencing the same issue.

https://play.decentraland.org/?position=-24%2C-9&realm=baldr&kernel-version=1.0.0-3184242384.commit-f8996b4

**Comment by seanellul** [comment]
Hey @kuruk-mm; this link worked with the UPS build, but unfortunately, it doesn't work for the Trilligent build found in the parcels below. The teleport to the location still jams at 47%.
```
  "scene": {
    "parcels": [
      "-20,26", "-19,26", 
      "-20,27", "-19,27"
     
    ],
    "base": "-20,26"
```

**Comment by seanellul** [comment]
New bugs on the UPS Property are appearing. 

https://vimeo.com/manage/videos/766510599/privacy

BUG FIRST NOTICED: 1/11/2022-2/11/2022
BUG WAS NOT HAPPENING ON: 31/10/2022 - 1/11/2022
LAST DEPLOY: 26/10/2022

**Comment by seanellul** [comment]
@Kinerius I'm not sure if there are any updates on this issue? However, the disappearing of avatars has left us all quite confused.

**Comment by xavi-dcl** [comment]
@popuz we were reviewing the board and this one is a bit stuck. Can you take a look at this?
