### ISSUE TITLE
Reopening Character runs automatically (on SDK) #361

### ISSUE THREAD

**Issue by Mjons** [decentraland/explorer-desktop#389]
### What happened?

This is was solved for me in-game. However when I am developing in the SDK and use 'dcl start' the issue persists where my character automatically runs in a single direction.

I am assuming this should be easy to fix since we patched it in-game already. Let's get it working in the SDK as well!

note that I have updated my SDK to thwe latest before reporting.

Thanks!

### Steps to reproduce

I simply dcl start in VS code and when the game loads up my character runs towards the camera. Same as in issue #361

### Operating System

Chrome Windows 10

### Wallet

Metamask

### CPU

Intel Core I9 10980XE

### GPU

NVIDIO Quadro P6000

### RAM

80GB

### Kernel Version

latest

### Unity Version

latest

### Realm

this only happens in SDK now

### NameTag

UnrealApe

**Comment by xavi-dcl** [comment]
Is this still happening? Should be solved as we upgrade Unity version

**Comment by Mjons** [comment]
Yes, it happens in sdk . Would be great to fix it..

But it did get fixed in the actual game.
