### ISSUE TITLE
unable to sign in via Metamask

### ISSUE THREAD

**Issue by alien35** [decentraland/explorer-desktop#394]
### What happened?

Clicking metamask prompts "WalletConnect" instead of "Metamask"

Uploading Screen Recording 2022-10-08 at 8.30.40 AM.mov…

### Steps to reproduce

click Metamask at the log in page

### Operating System

Mac OS X 11.1.0

### Wallet

Metamask

### CPU

Apple M1

### GPU

Apple M1 10922MB

### RAM

16384MB

### Kernel Version

1.0.0-3206567801.commit-8e217ff

### Unity Version

desktop-1.0.641-20221006152813.commit-5f8ac22

### Realm

heimdallr

### NameTag

test34333#010a

**Comment by JorgeDecentraland** [comment]
This is the expected behavior in desktop clients.

**Comment by JorgeDecentraland** [comment]
Metamask doesn't have a desktop wallet, this is the expected behavior.
The Metamask login is through their mobile wallet using WalletConnect
