### ISSUE TITLE
Ferris Wheel 3D asset doesn't render the first time the scene loads

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#400]
Steps to reproduce:
* Go to `-120,-103`
* Walk towards the `-119,-104` scene and observe that the Ferris Wheel mesh doesn't render
* Get away from the scene to unload it, get closer again to re-load it and observe that the mesh is now loaded

https://user-images.githubusercontent.com/1031741/197636126-e63402db-7ca3-4681-b55a-b9958e997044.mp4

**Comment by JorgeDecentraland** [comment]
Duplicated form #3284
