### ISSUE TITLE
Freezing when loading in alot of people in editor

### ISSUE THREAD

**Issue by TheShoes** [decentraland/explorer-desktop#406]
### What happened?

Hello, 

I have created dcl studio and one of the main components of it is to live on top of the desktop renderer.. 
Right now what I am seeing is if I just clone this GitHub and run it...

if I load into an empty or low occupancy scene it does just fine. 

but if I load into a scene with a lot of people it seems to freeze. 

Again this is without any of the dcl studio package installed. 

Should I be using a different branch or is my method the correct way.

Here is a video demo of it happening 
https://www.youtube.com/watch?v=qFotscV8Tzc

### Steps to reproduce

i load the project up in unity
if i go to land without people its fine
if i go to land with larger amounts of people unity freezes 

### Operating System

Windows 11

### Wallet

None, played as guest

### CPU

Processor	12th Gen Intel(R) Core(TM) i7-12800H, 2400 Mhz, 14 Core(s), 20 Logical Processor(s)

### GPU

Nvidia 3070ti

### RAM

16 Gig

### Kernel Version

1.0.0-3387732730.commit-b98547

### Unity Version

2020.3.34f1

**Comment by awedjob** [comment]
### Frozen DCL Scene in Unity Editor
I have recreated this same issue with a similar set up. After pressing play in the Unity Editor, the scene loads in the Loki realm. My avatar is the only one present in WonderMine. I change realms to the most populace at the time, Marvel. There's about 30 people at WonderMine and shortly after switching realms, the game tab and the scene tab for the Unity Editor are unresponsive.

I ended the Unity Editor task via Task Manager.

I also included the Task Manager processes and performance in the OBS screen recording. 

Here's a link to the video of my experience in WonderMine: [https://www.youtube.com/watch?v=uGOrTAoiiHc](https://www.youtube.com/watch?v=uGOrTAoiiHc)

**OS:** Windows 10 Pro (Version 22H2)
**Wallet:** Personal wallet via MetaMask
**Browser:** Chrome Version 107.0.5304.88 (Official Build) (64-bit)
**CPU:** Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz
**RAM:** 64.0 GB
**Unity Editor:** 2020.3.34f1
**Realm:** Loki, Marvel
**Coords:** -25,59

**Comment by eordano** [comment]
Extremely high priority before MVFW2023
