### ISSUE TITLE
DCL Browser Client Doesn't Connect from Unity Editor

### ISSUE THREAD

**Issue by awedjob** [decentraland/explorer-desktop#415]
### DCL Browser Client Won't Connect from Unity Editor 

Started up the Unity Editor. Specified the server and coordinates in the Debug Config panel to the right. Pressed the play button at the top of application. Chrome browser launched the DCL Client with the following in the address bar:

> https://play.decentraland.org/?NETWORK=mainnet&realm=loki&position=100%2C100&ws=wss://localhost:5000/dcl

After signing in using wallet, the application hangs indefinitely:
https://affirmativeorg.files.wordpress.com/2022/11/16nov2022-04.png

Here is a screenshot of the error messages from the Unity console:
https://affirmativeorg.files.wordpress.com/2022/11/16nov2022-03.png

Below is a link to a YT video showing the issue:
[https://youtu.be/XXmUKrnBLYY](https://youtu.be/XXmUKrnBLYY)

### Steps to reproduce

1. Start Unity Hub
2. Start unity-renderer-desktop from Projects
3. General Settings - Open Browser on Start & Web Socket SSL checked
4. Kernel General Settings - Specify "Realm" and "Start In" coordinates
5. Press Play
6. Choose "Play Using Your Wallet"
7. Sign in with Wallet

### Operating System

Windows 10 Pro (Version 22H2), Chrome Version 107.0.5304.88 (Official Build) (64-bit)

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz 3.60 GHz

### GPU

Raedon RX 460 - 4GB of DDR5 1750 MHz

### RAM

64.0 GB

### Kernel Version

2.0.0-3483139886.commit-136719a

### Unity Version

2020.3.34f1

### Realm

loki, dg

### NameTag

AwedJob

**Comment by shpkng** [comment]
try f12 in your browser and check if there are many websocket errors, it happens to me

**Comment by NeoDcl** [comment]
Hello ! Is this issue fixed? Please let me know how to fix it! Really appreciate your help. Thanks a lot fam
