### ISSUE TITLE
Avatar is Always running

### ISSUE THREAD

**Issue by pojitonov** [decentraland/explorer-desktop#425]
### What happened?

I am trying decentraland for some time, and my avatar is always running like crazy.
He stupps only when hit some object as obstacle.
Very strange experience.
I cant focus on any content since I just run.

### Steps to reproduce

Can't say anything.
I just installed fresh app and my avatar runs.
I have tried to reinstall several times nothing helps.

### Operating System

Windows 11  (10.0.22623) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 9 5900X 12-Core Processor 

### GPU

NVIDIA GeForce RTX 3080 10078MB

### RAM

130993MB

### Kernel Version

2.0.0-3499447167.commit-4753396

### Unity Version

desktop-1.0.805-20221116144427.commit-ad3486c

### Realm

artemis

### NameTag

Heamato#660d

**Comment by kwspgoliasz** [comment]
A fix was implemented in the past for a similar issue - [#396](https://github.com/decentraland/explorer-desktop/pull/396) Could you take a look if it was properly integrated?
