### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by bergome** [decentraland/explorer-desktop#479]
### What happened?

After a long absence of use, it stopped loading. Writes an error when loading:
SendMessage initializeMatrix has no receiver! 
![image](https://github.com/decentraland/explorer-desktop/assets/138132415/61954ccf-8698-457e-ad93-bc74e3fb7b14)
![image](https://github.com/decentraland/explorer-desktop/assets/138132415/bb793be2-db31-4534-b07b-1720eeee58e3)

### Steps to reproduce

1. Start Unity Hub
2. Start unity-renderer-desktop from Projects
3. General Settings - Open Browser on Start & Web Socket SSL checked
4. Kernel General Settings - Specify "Realm" and "Start In" coordinates
5. Press Play

### Operating System

Windows 10

### Wallet

Metamask

### CPU

I7-7700

### GPU

1050 TI

### RAM

16

### Kernel Version

-

### Unity Version

2021.3.14f1

### Realm

baldr

### NameTag

alex_berezin

**Comment by aixaCode** [comment]
@bergome Do you still experience the issue
